version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - cache

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-cache:/cachedata

volumes:
  redis-cache: